// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:damacafe/features/cafe/data/models/recipe_hive_model.dart';
import 'package:damacafe/features/character/data/models/character_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterHiveModelAdapter());
    registerAdapter(RecipeHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterHiveModelAdapter());
    registerAdapter(RecipeHiveModelAdapter());
  }
}
