import '../models/quest.dart';

class QuestDatabase {
  static const List<Quest> all = [
    // ── EXPLORATION / SAFE ──────────────────────────────────────────────
    Quest(
      id: 'exp_s_01',
      title: '한 블록 다른 길',
      description: '평소 가던 길에서 한 블록만 다른 길로 걸어보세요.\n익숙한 풍경이 조금 달라 보일 거예요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 3), StatBoost('spontaneity', 2)],
      emoji: '🚶',
    ),
    Quest(
      id: 'exp_s_02',
      title: '처음 보는 음료 고르기',
      description: '평소 주문하던 음료 대신, 메뉴판에서 한 번도 마셔보지 않은 음료를 골라보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('adaptability', 2)],
      emoji: '🥤',
    ),
    Quest(
      id: 'exp_s_03',
      title: '10분 폰 없이 걷기',
      description: '퇴근 또는 하교 후, 10분 동안 휴대폰 없이 걸어보세요.\n주변 소리와 풍경에 집중해보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('courage', 2)],
      emoji: '🌿',
    ),
    Quest(
      id: 'exp_s_04',
      title: '간판 읽기',
      description: '평소 아무 생각 없이 지나쳤던 간판이나 가게 이름 하나를 제대로 읽어보세요.\n그 이름에 담긴 의미를 상상해보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3)],
      emoji: '🏪',
    ),

    // ── EXPLORATION / NORMAL ────────────────────────────────────────────
    Quest(
      id: 'exp_n_01',
      title: '새로운 카페 입장',
      description: '한 번도 가보지 않은 카페에 혼자 들어가보세요.\n메뉴판을 천천히 읽고, 가장 낯선 메뉴를 골라보세요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('courage', 3)],
      emoji: '☕',
    ),
    Quest(
      id: 'exp_n_02',
      title: '다른 경로로 귀가',
      description: '퇴근 또는 하교 후, 평소와 완전히 다른 경로로 집에 가보세요.\n조금 돌아가도 괜찮아요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('spontaneity', 3)],
      emoji: '🗺️',
    ),
    Quest(
      id: 'exp_n_03',
      title: '한 번도 안 들어간 가게',
      description: '동네에서 지나치기만 했던 가게에 오늘 처음 들어가보세요.\n살 것이 없어도 구경만 해도 됩니다.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('courage', 2)],
      emoji: '🛍️',
    ),
    Quest(
      id: 'exp_n_04',
      title: '처음 가는 공원',
      description: '집 근처에서 한 번도 가지 않았던 공원이나 광장을 찾아가보세요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('action', 2)],
      emoji: '🌳',
    ),

    // ── EXPLORATION / CHALLENGE ─────────────────────────────────────────
    Quest(
      id: 'exp_c_01',
      title: '낯선 동네 30분 탐험',
      description: '한 번도 가보지 않은 동네에서 혼자 30분 동안 걸어보세요.\n목적지 없이, 그냥 발길이 닿는 대로.',
      category: QuestCategory.exploration,
      difficulty: 3,
      baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 7), StatBoost('courage', 5)],
      emoji: '🏙️',
    ),
    Quest(
      id: 'exp_c_02',
      title: '처음 보는 음식 주문',
      description: '한 번도 먹어본 적 없는 음식이나 요리를 오늘 주문해보세요.\n레시피를 모른 채 먹어보는 것도 경험입니다.',
      category: QuestCategory.exploration,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 5), StatBoost('adaptability', 5)],
      emoji: '🍜',
    ),

    // ── EXPLORATION / CRAZY ─────────────────────────────────────────────
    Quest(
      id: 'exp_z_01',
      title: '목적지 없이 지하철 타기',
      description: '퇴근 후 목적지를 정하지 말고 지하철에 타세요.\n세 정거장을 이동한 뒤 그 역 주변을 탐험해보세요.',
      category: QuestCategory.exploration,
      difficulty: 5,
      baseXP: 250,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 10), StatBoost('spontaneity', 8), StatBoost('courage', 5)],
      emoji: '🚇',
    ),
    Quest(
      id: 'exp_z_02',
      title: '메뉴판 없이 주문',
      description: '처음 가는 식당에서 메뉴판을 보지 않고 직원에게 "오늘 가장 추천하는 메뉴"를 달라고 해보세요.',
      category: QuestCategory.exploration,
      difficulty: 4,
      baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 7), StatBoost('social', 5), StatBoost('courage', 5)],
      emoji: '🎲',
    ),

    // ── SOCIAL / SAFE ───────────────────────────────────────────────────
    Quest(
      id: 'soc_s_01',
      title: '스쳐가는 사람에게 미소',
      description: '오늘 지나치는 사람 한 명에게 자연스럽게 미소를 지어보세요.\n말이 필요 없어요.',
      category: QuestCategory.social,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3)],
      emoji: '😊',
    ),
    Quest(
      id: 'soc_s_02',
      title: '직원에게 짧은 인사',
      description: '카페나 편의점 직원에게 "날씨 좋네요" 한 마디를 건네보세요.\n진심 담긴 짧은 말 한마디로 충분합니다.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 80,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 4), StatBoost('courage', 2)],
      emoji: '💬',
    ),

    // ── SOCIAL / NORMAL ─────────────────────────────────────────────────
    Quest(
      id: 'soc_n_01',
      title: '안 보이던 지인에게 안부',
      description: '최근 연락하지 않았던 지인에게 짧은 안부 메시지를 보내보세요.\n"잘 지내?" 한 마디로 시작해도 됩니다.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('relationship', 3)],
      emoji: '📱',
    ),
    Quest(
      id: 'soc_n_02',
      title: '오늘 처음 찍은 사진 공유',
      description: '오늘 처음 찍은 사진 한 장을 친구에게 전송하고 이유를 짧게 설명해보세요.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 4), StatBoost('creativity', 2)],
      emoji: '📸',
    ),
    Quest(
      id: 'soc_n_03',
      title: '카페에서 메뉴 추천받기',
      description: '카페에서 직원에게 "오늘 뭐가 제일 맛있어요?"라고 진심으로 물어보세요.\n추천받은 메뉴를 주문하면 완벽합니다.',
      category: QuestCategory.social,
      difficulty: 3,
      baseXP: 120,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('courage', 4)],
      emoji: '🧋',
    ),

    // ── SOCIAL / CHALLENGE ──────────────────────────────────────────────
    Quest(
      id: 'soc_c_01',
      title: '잘 안 말걸던 동료에게 먼저',
      description: '평소 잘 대화하지 않는 동료에게 먼저 말을 걸어보세요.\n업무 얘기가 아니어도 됩니다.',
      category: QuestCategory.social,
      difficulty: 3,
      baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 5)],
      emoji: '🤝',
    ),

    // ── SOCIAL / CRAZY ──────────────────────────────────────────────────
    Quest(
      id: 'soc_z_01',
      title: '낯선 사람에게 질문 하나',
      description: '길을 걷다가 낯선 사람에게 간단하고 자연스러운 질문 하나를 해보세요.\n"이 근처에 괜찮은 카페 알아요?" 같은 것으로 충분합니다.',
      category: QuestCategory.social,
      difficulty: 4,
      baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 8), StatBoost('courage', 7)],
      emoji: '🗣️',
    ),

    // ── CREATIVE / SAFE ─────────────────────────────────────────────────
    Quest(
      id: 'cre_s_01',
      title: '눈에 띄는 장면 찍기',
      description: '오늘 이동 중에 가장 인상적으로 느껴지는 장면을 스마트폰으로 한 장 찍어보세요.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3)],
      emoji: '📷',
    ),
    Quest(
      id: 'cre_s_02',
      title: '3줄 일기',
      description: '오늘 있었던 일을 딱 3줄로 써보세요.\n완성도는 중요하지 않습니다.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3), StatBoost('thinking', 2)],
      emoji: '📝',
    ),
    Quest(
      id: 'cre_s_03',
      title: '이모지 5개로 오늘 표현하기',
      description: '오늘 느낀 감정 또는 있었던 일을 이모지 5개로만 표현해보세요.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4)],
      emoji: '🎭',
    ),

    // ── CREATIVE / NORMAL ───────────────────────────────────────────────
    Quest(
      id: 'cre_n_01',
      title: '주변 물건으로 작은 작품',
      description: '지금 주변에 있는 물건들로 작은 배치 작품을 만들어보세요.\n사진으로 찍어두면 더 좋습니다.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('spontaneity', 3)],
      emoji: '🎨',
    ),
    Quest(
      id: 'cre_n_02',
      title: '낯선 장르의 음악 듣기',
      description: '평소 절대 안 듣는 장르의 음악 플레이리스트를 하나 찾아 10분 동안 들어보세요.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 4), StatBoost('adaptability', 3)],
      emoji: '🎵',
    ),
    Quest(
      id: 'cre_n_03',
      title: '오늘의 풍경 스케치',
      description: '오늘 본 풍경이나 물건을 간단하게 스케치해보세요.\n잘 그리지 않아도 됩니다. 그리는 행위 자체가 목표입니다.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 6), StatBoost('thinking', 2)],
      emoji: '✏️',
    ),

    // ── CREATIVE / CHALLENGE ────────────────────────────────────────────
    Quest(
      id: 'cre_c_01',
      title: '혼자 노래 한 곡 끝까지',
      description: '혼자 있는 공간에서 좋아하는 노래 한 곡을 처음부터 끝까지 불러보세요.',
      category: QuestCategory.creative,
      difficulty: 3,
      baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 6), StatBoost('courage', 4)],
      emoji: '🎤',
    ),
    Quest(
      id: 'cre_c_02',
      title: '오늘을 시로 쓰기',
      description: '오늘 하루를 4줄짜리 시로 표현해보세요.\n운율이나 형식은 전혀 중요하지 않습니다.',
      category: QuestCategory.creative,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('thinking', 4)],
      emoji: '🖊️',
    ),

    // ── CREATIVE / CRAZY ────────────────────────────────────────────────
    Quest(
      id: 'cre_z_01',
      title: '30초 즉흥 연주',
      description: '어떤 물건이든 악기처럼 사용해 30초짜리 즉흥 퍼포먼스를 해보세요.\n녹음하면 더욱 완벽합니다.',
      category: QuestCategory.creative,
      difficulty: 4,
      baseXP: 190,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 8), StatBoost('spontaneity', 7), StatBoost('courage', 4)],
      emoji: '🥁',
    ),

    // ── THINKING / SAFE ─────────────────────────────────────────────────
    Quest(
      id: 'thi_s_01',
      title: '평소 못 본 것 하나 찾기',
      description: '오늘 이동 중 평소에 눈치채지 못했던 것을 하나 발견해보세요.\n벽화, 식물, 간판 하나라도 충분합니다.',
      category: QuestCategory.thinking,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('exploration', 2)],
      emoji: '🔍',
    ),
    Quest(
      id: 'thi_s_02',
      title: '스쳐간 사람의 하루 상상하기',
      description: '오늘 지나친 사람 중 한 명을 골라 그 사람의 오늘 하루를 마음속으로 상상해보세요.',
      category: QuestCategory.thinking,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 4)],
      emoji: '💭',
    ),

    // ── THINKING / NORMAL ───────────────────────────────────────────────
    Quest(
      id: 'thi_n_01',
      title: '반대 의견으로 스스로 설득',
      description: '평소 강하게 믿는 생각 하나를 선택해, 그 반대 입장에서 스스로를 설득해보세요.',
      category: QuestCategory.thinking,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('adaptability', 3)],
      emoji: '⚖️',
    ),
    Quest(
      id: 'thi_n_02',
      title: '오늘 대화에서 왜? 세 번 더',
      description: '오늘 누군가와 대화할 때 평소보다 "왜?"를 세 번 더 물어보세요.\n깊은 대화가 시작될 수 있어요.',
      category: QuestCategory.thinking,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('social', 2)],
      emoji: '❓',
    ),

    // ── THINKING / CHALLENGE ────────────────────────────────────────────
    Quest(
      id: 'thi_c_01',
      title: '당연한 것에 의문 품기',
      description: '오늘 당연하다고 생각했던 것 하나에 "왜 이렇게 해야 하지?"라는 의문을 품어보세요.\n답을 찾지 않아도 됩니다.',
      category: QuestCategory.thinking,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('courage', 3)],
      emoji: '🤔',
    ),

    // ── ACTION / SAFE ───────────────────────────────────────────────────
    Quest(
      id: 'act_s_01',
      title: '10분 빠르게 걷기',
      description: '오늘 퇴근 또는 하교 후 10분 동안 평소보다 조금 빠르게 걸어보세요.',
      category: QuestCategory.action,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3)],
      emoji: '⚡',
    ),
    Quest(
      id: 'act_s_02',
      title: '엘리베이터 대신 계단',
      description: '오늘 이동 중 엘리베이터나 에스컬레이터 대신 계단을 이용해보세요.',
      category: QuestCategory.action,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 4), StatBoost('courage', 1)],
      emoji: '🪜',
    ),

    // ── ACTION / NORMAL ─────────────────────────────────────────────────
    Quest(
      id: 'act_n_01',
      title: '30분 바깥 걷기',
      description: '30분 동안 목적 없이 밖에서 걸어보세요.\n이어폰 없이 걸으면 더 효과적입니다.',
      category: QuestCategory.action,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('thinking', 2)],
      emoji: '🌆',
    ),
    Quest(
      id: 'act_n_02',
      title: '처음 보는 운동 영상 따라하기',
      description: '유튜브에서 한 번도 해본 적 없는 운동 영상을 찾아서 10분만 따라해보세요.',
      category: QuestCategory.action,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('adaptability', 3)],
      emoji: '🏋️',
    ),

    // ── ACTION / CHALLENGE ──────────────────────────────────────────────
    Quest(
      id: 'act_c_01',
      title: '새로운 운동 시도',
      description: '평소 한 번도 해보지 않은 운동을 오늘 시도해보세요.\n클라이밍, 요가, 탁구, 수영 무엇이든 괜찮습니다.',
      category: QuestCategory.action,
      difficulty: 4,
      baseXP: 180,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 5), StatBoost('exploration', 3)],
      emoji: '🧗',
    ),

    // ── ACTION / CRAZY ──────────────────────────────────────────────────
    Quest(
      id: 'act_z_01',
      title: '즉흥 활동 예약',
      description: '지금 이 순간, 평소 절대 하지 않을 것 같은 활동을 즉흥적으로 예약하거나 신청해보세요.',
      category: QuestCategory.action,
      difficulty: 5,
      baseXP: 240,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 8), StatBoost('spontaneity', 10), StatBoost('courage', 6)],
      emoji: '🎯',
    ),

    // ── RELATIONSHIP / SAFE ─────────────────────────────────────────────
    Quest(
      id: 'rel_s_01',
      title: '가족에게 "요즘 어때?" 묻기',
      description: '가족 한 명에게 오늘 "요즘 어때?"라고 먼저 물어보세요.\n문자도 괜찮습니다.',
      category: QuestCategory.relationship,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 2)],
      emoji: '❤️',
    ),
    Quest(
      id: 'rel_s_02',
      title: '친구에게 감사 메시지',
      description: '친구 한 명을 떠올리며 짧은 감사 메시지를 보내보세요.\n이유는 사소해도 됩니다.',
      category: QuestCategory.relationship,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 3)],
      emoji: '🙏',
    ),

    // ── RELATIONSHIP / NORMAL ───────────────────────────────────────────
    Quest(
      id: 'rel_n_01',
      title: '오래된 친구에게 연락',
      description: '최근 6개월 이상 연락하지 않은 친구에게 오늘 연락해보세요.',
      category: QuestCategory.relationship,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 4), StatBoost('courage', 2)],
      emoji: '🔗',
    ),
    Quest(
      id: 'rel_n_02',
      title: '직접 감사 표현',
      description: '소중한 사람에게 문자가 아닌 직접 말로 감사하다고 전해보세요.',
      category: QuestCategory.relationship,
      difficulty: 2,
      baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('courage', 4)],
      emoji: '💝',
    ),

    // ── RELATIONSHIP / CHALLENGE ────────────────────────────────────────
    Quest(
      id: 'rel_c_01',
      title: '친구에게 갑자기 만나자',
      description: '친구 한 명에게 "지금 시간 돼? 잠깐 볼래?"라고 즉흥적으로 연락해보세요.',
      category: QuestCategory.relationship,
      difficulty: 3,
      baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('spontaneity', 6), StatBoost('social', 4)],
      emoji: '🤗',
    ),

    // ── RANDOM ──────────────────────────────────────────────────────────
    Quest(
      id: 'rnd_01',
      title: '5분 명상',
      description: '지금 바로 5분 동안 눈을 감고 호흡에만 집중해보세요.\n생각이 많아도 괜찮습니다.',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 4), StatBoost('adaptability', 3)],
      emoji: '🧘',
    ),
    Quest(
      id: 'rnd_02',
      title: '동전으로 결정',
      description: '오늘 작은 선택 하나를 동전 던지기로 결정해보세요.\n저녁 메뉴, 이동 방향 무엇이든 좋습니다.',
      category: QuestCategory.random,
      difficulty: 1,
      baseXP: 70,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('spontaneity', 5)],
      emoji: '🪙',
    ),
    Quest(
      id: 'rnd_03',
      title: '오늘의 다짐 하나',
      description: '오늘 하루 동안 지킬 작은 규칙 하나를 스스로 만들어보세요.\n예: "오늘은 엘리베이터 안 탄다"',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('courage', 3), StatBoost('adaptability', 3)],
      emoji: '🎯',
    ),
    Quest(
      id: 'rnd_04',
      title: '버킷리스트 하나 적기',
      description: '언젠가 해보고 싶은 것을 딱 하나 적어두세요.\n실현 가능 여부는 중요하지 않습니다.',
      category: QuestCategory.random,
      difficulty: 1,
      baseXP: 65,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('spontaneity', 3), StatBoost('creativity', 3)],
      emoji: '📋',
    ),
    Quest(
      id: 'rnd_05',
      title: '평소 안 보던 콘텐츠 끝까지 보기',
      description: '평소 관심 없던 장르의 영상이나 글을 하나 선택해서 끝까지 보세요.',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('adaptability', 4), StatBoost('thinking', 3)],
      emoji: '📺',
    ),
  ];

  static Quest? findById(String id) {
    try {
      return all.firstWhere((q) => q.id == id);
    } catch (_) {
      return null;
    }
  }
}
