import '../models/quest.dart';

class QuestDatabase {
  static const List<Quest> all = [
    // ── EXPLORATION / SAFE ──────────────────────────────────────────────
    Quest(
      id: 'exp_s_01',
      title: '한 블록 다른 길',
      description: '평소 가던 길에서 한 블록만 다른 길로 걸어보세요.\n익숙한 풍경이 조금 달라 보일 거예요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 3), StatBoost('spontaneity', 2)],
      emoji: '🚶',
    ),
    Quest(
      id: 'exp_s_02',
      title: '처음 보는 음료 고르기',
      description: '평소 주문하던 음료 대신, 메뉴판에서 한 번도 마셔보지 않은 음료를 골라보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('adaptability', 2)],
      emoji: '🥤',
    ),
    Quest(
      id: 'exp_s_03',
      title: '10분 폰 없이 걷기',
      description: '퇴근 또는 하교 후, 10분 동안 휴대폰 없이 걸어보세요.\n주변 소리와 풍경에 집중해보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('courage', 2)],
      emoji: '🌿',
    ),
    Quest(
      id: 'exp_s_04',
      title: '간판 읽기',
      description: '평소 아무 생각 없이 지나쳤던 간판이나 가게 이름 하나를 제대로 읽어보세요.\n그 이름에 담긴 의미를 상상해보세요.',
      category: QuestCategory.exploration,
      difficulty: 1,
      baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3)],
      emoji: '🏪',
    ),

    // ── EXPLORATION / NORMAL ────────────────────────────────────────────
    Quest(
      id: 'exp_n_01',
      title: '새로운 카페 입장',
      description: '한 번도 가보지 않은 카페에 혼자 들어가보세요.\n메뉴판을 천천히 읽고, 가장 낯선 메뉴를 골라보세요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('courage', 3)],
      emoji: '☕',
    ),
    Quest(
      id: 'exp_n_02',
      title: '다른 경로로 귀가',
      description: '퇴근 또는 하교 후, 평소와 완전히 다른 경로로 집에 가보세요.\n조금 돌아가도 괜찮아요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('spontaneity', 3)],
      emoji: '🗺️',
    ),
    Quest(
      id: 'exp_n_03',
      title: '한 번도 안 들어간 가게',
      description: '동네에서 지나치기만 했던 가게에 오늘 처음 들어가보세요.\n살 것이 없어도 구경만 해도 됩니다.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('courage', 2)],
      emoji: '🛍️',
    ),
    Quest(
      id: 'exp_n_04',
      title: '처음 가는 공원',
      description: '집 근처에서 한 번도 가지 않았던 공원이나 광장을 찾아가보세요.',
      category: QuestCategory.exploration,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('action', 2)],
      emoji: '🌳',
    ),

    // ── EXPLORATION / CHALLENGE ─────────────────────────────────────────
    Quest(
      id: 'exp_c_01',
      title: '낯선 동네 30분 탐험',
      description: '한 번도 가보지 않은 동네에서 혼자 30분 동안 걸어보세요.\n목적지 없이, 그냥 발길이 닿는 대로.',
      category: QuestCategory.exploration,
      difficulty: 3,
      baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 7), StatBoost('courage', 5)],
      emoji: '🏙️',
    ),
    Quest(
      id: 'exp_c_02',
      title: '처음 보는 음식 주문',
      description: '한 번도 먹어본 적 없는 음식이나 요리를 오늘 주문해보세요.\n레시피를 모른 채 먹어보는 것도 경험입니다.',
      category: QuestCategory.exploration,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 5), StatBoost('adaptability', 5)],
      emoji: '🍜',
    ),

    // ── EXPLORATION / CRAZY ─────────────────────────────────────────────
    Quest(
      id: 'exp_z_01',
      title: '목적지 없이 지하철 타기',
      description: '퇴근 후 목적지를 정하지 말고 지하철에 타세요.\n세 정거장을 이동한 뒤 그 역 주변을 탐험해보세요.',
      category: QuestCategory.exploration,
      difficulty: 5,
      baseXP: 250,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 10), StatBoost('spontaneity', 8), StatBoost('courage', 5)],
      emoji: '🚇',
    ),
    Quest(
      id: 'exp_z_02',
      title: '메뉴판 없이 주문',
      description: '처음 가는 식당에서 메뉴판을 보지 않고 직원에게 "오늘 가장 추천하는 메뉴"를 달라고 해보세요.',
      category: QuestCategory.exploration,
      difficulty: 4,
      baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 7), StatBoost('social', 5), StatBoost('courage', 5)],
      emoji: '🎲',
    ),

    // ── SOCIAL / SAFE ───────────────────────────────────────────────────
    Quest(
      id: 'soc_s_01',
      title: '스쳐가는 사람에게 미소',
      description: '오늘 지나치는 사람 한 명에게 자연스럽게 미소를 지어보세요.\n말이 필요 없어요.',
      category: QuestCategory.social,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3)],
      emoji: '😊',
    ),
    Quest(
      id: 'soc_s_02',
      title: '직원에게 짧은 인사',
      description: '카페나 편의점 직원에게 "날씨 좋네요" 한 마디를 건네보세요.\n진심 담긴 짧은 말 한마디로 충분합니다.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 80,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 4), StatBoost('courage', 2)],
      emoji: '💬',
    ),

    // ── SOCIAL / NORMAL ─────────────────────────────────────────────────
    Quest(
      id: 'soc_n_01',
      title: '안 보이던 지인에게 안부',
      description: '최근 연락하지 않았던 지인에게 짧은 안부 메시지를 보내보세요.\n"잘 지내?" 한 마디로 시작해도 됩니다.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('relationship', 3)],
      emoji: '📱',
    ),
    Quest(
      id: 'soc_n_02',
      title: '오늘 처음 찍은 사진 공유',
      description: '오늘 처음 찍은 사진 한 장을 친구에게 전송하고 이유를 짧게 설명해보세요.',
      category: QuestCategory.social,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 4), StatBoost('creativity', 2)],
      emoji: '📸',
    ),
    Quest(
      id: 'soc_n_03',
      title: '카페에서 메뉴 추천받기',
      description: '카페에서 직원에게 "오늘 뭐가 제일 맛있어요?"라고 진심으로 물어보세요.\n추천받은 메뉴를 주문하면 완벽합니다.',
      category: QuestCategory.social,
      difficulty: 3,
      baseXP: 120,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('courage', 4)],
      emoji: '🧋',
    ),

    // ── SOCIAL / CHALLENGE ──────────────────────────────────────────────
    Quest(
      id: 'soc_c_01',
      title: '잘 안 말걸던 동료에게 먼저',
      description: '평소 잘 대화하지 않는 동료에게 먼저 말을 걸어보세요.\n업무 얘기가 아니어도 됩니다.',
      category: QuestCategory.social,
      difficulty: 3,
      baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 5)],
      emoji: '🤝',
    ),

    // ── SOCIAL / CRAZY ──────────────────────────────────────────────────
    Quest(
      id: 'soc_z_01',
      title: '낯선 사람에게 질문 하나',
      description: '길을 걷다가 낯선 사람에게 간단하고 자연스러운 질문 하나를 해보세요.\n"이 근처에 괜찮은 카페 알아요?" 같은 것으로 충분합니다.',
      category: QuestCategory.social,
      difficulty: 4,
      baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 8), StatBoost('courage', 7)],
      emoji: '🗣️',
    ),

    // ── CREATIVE / SAFE ─────────────────────────────────────────────────
    Quest(
      id: 'cre_s_01',
      title: '눈에 띄는 장면 찍기',
      description: '오늘 이동 중에 가장 인상적으로 느껴지는 장면을 스마트폰으로 한 장 찍어보세요.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3)],
      emoji: '📷',
    ),
    Quest(
      id: 'cre_s_02',
      title: '3줄 일기',
      description: '오늘 있었던 일을 딱 3줄로 써보세요.\n완성도는 중요하지 않습니다.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3), StatBoost('thinking', 2)],
      emoji: '📝',
    ),
    Quest(
      id: 'cre_s_03',
      title: '이모지 5개로 오늘 표현하기',
      description: '오늘 느낀 감정 또는 있었던 일을 이모지 5개로만 표현해보세요.',
      category: QuestCategory.creative,
      difficulty: 1,
      baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4)],
      emoji: '🎭',
    ),

    // ── CREATIVE / NORMAL ───────────────────────────────────────────────
    Quest(
      id: 'cre_n_01',
      title: '주변 물건으로 작은 작품',
      description: '지금 주변에 있는 물건들로 작은 배치 작품을 만들어보세요.\n사진으로 찍어두면 더 좋습니다.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('spontaneity', 3)],
      emoji: '🎨',
    ),
    Quest(
      id: 'cre_n_02',
      title: '낯선 장르의 음악 듣기',
      description: '평소 절대 안 듣는 장르의 음악 플레이리스트를 하나 찾아 10분 동안 들어보세요.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 4), StatBoost('adaptability', 3)],
      emoji: '🎵',
    ),
    Quest(
      id: 'cre_n_03',
      title: '오늘의 풍경 스케치',
      description: '오늘 본 풍경이나 물건을 간단하게 스케치해보세요.\n잘 그리지 않아도 됩니다. 그리는 행위 자체가 목표입니다.',
      category: QuestCategory.creative,
      difficulty: 2,
      baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 6), StatBoost('thinking', 2)],
      emoji: '✏️',
    ),

    // ── CREATIVE / CHALLENGE ────────────────────────────────────────────
    Quest(
      id: 'cre_c_01',
      title: '혼자 노래 한 곡 끝까지',
      description: '혼자 있는 공간에서 좋아하는 노래 한 곡을 처음부터 끝까지 불러보세요.',
      category: QuestCategory.creative,
      difficulty: 3,
      baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 6), StatBoost('courage', 4)],
      emoji: '🎤',
    ),
    Quest(
      id: 'cre_c_02',
      title: '오늘을 시로 쓰기',
      description: '오늘 하루를 4줄짜리 시로 표현해보세요.\n운율이나 형식은 전혀 중요하지 않습니다.',
      category: QuestCategory.creative,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('thinking', 4)],
      emoji: '🖊️',
    ),

    // ── CREATIVE / CRAZY ────────────────────────────────────────────────
    Quest(
      id: 'cre_z_01',
      title: '30초 즉흥 연주',
      description: '어떤 물건이든 악기처럼 사용해 30초짜리 즉흥 퍼포먼스를 해보세요.\n녹음하면 더욱 완벽합니다.',
      category: QuestCategory.creative,
      difficulty: 4,
      baseXP: 190,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 8), StatBoost('spontaneity', 7), StatBoost('courage', 4)],
      emoji: '🥁',
    ),

    // ── THINKING / SAFE ─────────────────────────────────────────────────
    Quest(
      id: 'thi_s_01',
      title: '평소 못 본 것 하나 찾기',
      description: '오늘 이동 중 평소에 눈치채지 못했던 것을 하나 발견해보세요.\n벽화, 식물, 간판 하나라도 충분합니다.',
      category: QuestCategory.thinking,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('exploration', 2)],
      emoji: '🔍',
    ),
    Quest(
      id: 'thi_s_02',
      title: '스쳐간 사람의 하루 상상하기',
      description: '오늘 지나친 사람 중 한 명을 골라 그 사람의 오늘 하루를 마음속으로 상상해보세요.',
      category: QuestCategory.thinking,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 4)],
      emoji: '💭',
    ),

    // ── THINKING / NORMAL ───────────────────────────────────────────────
    Quest(
      id: 'thi_n_01',
      title: '반대 의견으로 스스로 설득',
      description: '평소 강하게 믿는 생각 하나를 선택해, 그 반대 입장에서 스스로를 설득해보세요.',
      category: QuestCategory.thinking,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('adaptability', 3)],
      emoji: '⚖️',
    ),
    Quest(
      id: 'thi_n_02',
      title: '오늘 대화에서 왜? 세 번 더',
      description: '오늘 누군가와 대화할 때 평소보다 "왜?"를 세 번 더 물어보세요.\n깊은 대화가 시작될 수 있어요.',
      category: QuestCategory.thinking,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('social', 2)],
      emoji: '❓',
    ),

    // ── THINKING / CHALLENGE ────────────────────────────────────────────
    Quest(
      id: 'thi_c_01',
      title: '당연한 것에 의문 품기',
      description: '오늘 당연하다고 생각했던 것 하나에 "왜 이렇게 해야 하지?"라는 의문을 품어보세요.\n답을 찾지 않아도 됩니다.',
      category: QuestCategory.thinking,
      difficulty: 3,
      baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('courage', 3)],
      emoji: '🤔',
    ),

    // ── ACTION / SAFE ───────────────────────────────────────────────────
    Quest(
      id: 'act_s_01',
      title: '10분 빠르게 걷기',
      description: '오늘 퇴근 또는 하교 후 10분 동안 평소보다 조금 빠르게 걸어보세요.',
      category: QuestCategory.action,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3)],
      emoji: '⚡',
    ),
    Quest(
      id: 'act_s_02',
      title: '엘리베이터 대신 계단',
      description: '오늘 이동 중 엘리베이터나 에스컬레이터 대신 계단을 이용해보세요.',
      category: QuestCategory.action,
      difficulty: 1,
      baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 4), StatBoost('courage', 1)],
      emoji: '🪜',
    ),

    // ── ACTION / NORMAL ─────────────────────────────────────────────────
    Quest(
      id: 'act_n_01',
      title: '30분 바깥 걷기',
      description: '30분 동안 목적 없이 밖에서 걸어보세요.\n이어폰 없이 걸으면 더 효과적입니다.',
      category: QuestCategory.action,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('thinking', 2)],
      emoji: '🌆',
    ),
    Quest(
      id: 'act_n_02',
      title: '처음 보는 운동 영상 따라하기',
      description: '유튜브에서 한 번도 해본 적 없는 운동 영상을 찾아서 10분만 따라해보세요.',
      category: QuestCategory.action,
      difficulty: 2,
      baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('adaptability', 3)],
      emoji: '🏋️',
    ),

    // ── ACTION / CHALLENGE ──────────────────────────────────────────────
    Quest(
      id: 'act_c_01',
      title: '새로운 운동 시도',
      description: '평소 한 번도 해보지 않은 운동을 오늘 시도해보세요.\n클라이밍, 요가, 탁구, 수영 무엇이든 괜찮습니다.',
      category: QuestCategory.action,
      difficulty: 4,
      baseXP: 180,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 5), StatBoost('exploration', 3)],
      emoji: '🧗',
    ),

    // ── ACTION / CRAZY ──────────────────────────────────────────────────
    Quest(
      id: 'act_z_01',
      title: '즉흥 활동 예약',
      description: '지금 이 순간, 평소 절대 하지 않을 것 같은 활동을 즉흥적으로 예약하거나 신청해보세요.',
      category: QuestCategory.action,
      difficulty: 5,
      baseXP: 240,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 8), StatBoost('spontaneity', 10), StatBoost('courage', 6)],
      emoji: '🎯',
    ),

    // ── RELATIONSHIP / SAFE ─────────────────────────────────────────────
    Quest(
      id: 'rel_s_01',
      title: '가족에게 "요즘 어때?" 묻기',
      description: '가족 한 명에게 오늘 "요즘 어때?"라고 먼저 물어보세요.\n문자도 괜찮습니다.',
      category: QuestCategory.relationship,
      difficulty: 1,
      baseXP: 60,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 2)],
      emoji: '❤️',
    ),
    Quest(
      id: 'rel_s_02',
      title: '친구에게 감사 메시지',
      description: '친구 한 명을 떠올리며 짧은 감사 메시지를 보내보세요.\n이유는 사소해도 됩니다.',
      category: QuestCategory.relationship,
      difficulty: 1,
      baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 3)],
      emoji: '🙏',
    ),

    // ── RELATIONSHIP / NORMAL ───────────────────────────────────────────
    Quest(
      id: 'rel_n_01',
      title: '오래된 친구에게 연락',
      description: '최근 6개월 이상 연락하지 않은 친구에게 오늘 연락해보세요.',
      category: QuestCategory.relationship,
      difficulty: 2,
      baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 4), StatBoost('courage', 2)],
      emoji: '🔗',
    ),
    Quest(
      id: 'rel_n_02',
      title: '직접 감사 표현',
      description: '소중한 사람에게 문자가 아닌 직접 말로 감사하다고 전해보세요.',
      category: QuestCategory.relationship,
      difficulty: 2,
      baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('courage', 4)],
      emoji: '💝',
    ),

    // ── RELATIONSHIP / CHALLENGE ────────────────────────────────────────
    Quest(
      id: 'rel_c_01',
      title: '친구에게 갑자기 만나자',
      description: '친구 한 명에게 "지금 시간 돼? 잠깐 볼래?"라고 즉흥적으로 연락해보세요.',
      category: QuestCategory.relationship,
      difficulty: 3,
      baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('spontaneity', 6), StatBoost('social', 4)],
      emoji: '🤗',
    ),

    // ── EXPLORATION / SAFE (추가) ───────────────────────────────────────
    Quest(
      id: 'exp2_s_01', title: '하늘 사진 다섯 장',
      description: '걸어가면서 서로 다른 각도로 하늘 사진 5장을 찍어보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2)], emoji: '☁️',
    ),
    Quest(
      id: 'exp2_s_02', title: '주변 소리 세 가지',
      description: '눈을 감고 30초 동안 주변 소리를 듣고 세 가지를 찾아보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('thinking', 1)], emoji: '👂',
    ),
    Quest(
      id: 'exp2_s_03', title: '동네 이름 유래 검색',
      description: '지금 있는 동네 이름이 왜 그 이름인지 검색해보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('thinking', 2)], emoji: '📍',
    ),
    Quest(
      id: 'exp2_s_04', title: '편의점 신상 먹어보기',
      description: '편의점에서 처음 보는 신제품 하나를 골라 먹어보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('spontaneity', 2)], emoji: '🍡',
    ),
    Quest(
      id: 'exp2_s_05', title: '창밖 10분 관찰',
      description: '지금 있는 곳 창문 밖을 10분 동안 조용히 바라보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('thinking', 2)], emoji: '🪟',
    ),
    Quest(
      id: 'exp2_s_06', title: '가장 오래된 물건 찾기',
      description: '지금 있는 공간에서 가장 오래된 물건 하나를 찾아보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('thinking', 2)], emoji: '🗿',
    ),
    Quest(
      id: 'exp2_s_07', title: '위성뷰로 동네 보기',
      description: '지도 앱에서 위성뷰로 내 동네를 10분 탐색해보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 35,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2)], emoji: '🛰️',
    ),
    Quest(
      id: 'exp2_s_08', title: '오늘의 냄새 기록',
      description: '이동 중 인상적인 냄새를 3가지 기억해두고 기록해보세요.',
      category: QuestCategory.exploration, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('exploration', 2), StatBoost('creativity', 1)], emoji: '🌸',
    ),

    // ── EXPLORATION / NORMAL (추가) ─────────────────────────────────────
    Quest(
      id: 'exp2_n_01', title: '재래시장 구경',
      description: '처음 가보는 재래시장이나 전통 시장을 30분 이상 구경해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('social', 2)], emoji: '🏮',
    ),
    Quest(
      id: 'exp2_n_02', title: '동네 서점 탐방',
      description: '동네 작은 서점에서 1시간 동안 책을 구경해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('thinking', 3)], emoji: '📚',
    ),
    Quest(
      id: 'exp2_n_03', title: '야경 보러 가기',
      description: '가까운 야경 명소를 찾아 30분 이상 감상해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('creativity', 2)], emoji: '🌃',
    ),
    Quest(
      id: 'exp2_n_04', title: '박물관·미술관 방문',
      description: '근처 박물관이나 미술관에 혼자 방문해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('creativity', 3)], emoji: '🖼️',
    ),
    Quest(
      id: 'exp2_n_05', title: '새 산책로 발견',
      description: '평소 안 가던 산책로나 트레킹 코스를 하나 찾아 걸어보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('action', 3)], emoji: '🌲',
    ),
    Quest(
      id: 'exp2_n_06', title: '버스 타고 멀리까지',
      description: '버스 창가에 앉아 평소보다 두 정거장 더 타고 내려보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('spontaneity', 2)], emoji: '🚌',
    ),
    Quest(
      id: 'exp2_n_07', title: '공공도서관 방문',
      description: '자주 안 가는 공공도서관에서 30분 이상 시간을 보내보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 3), StatBoost('thinking', 4)], emoji: '🏛️',
    ),
    Quest(
      id: 'exp2_n_08', title: '낯선 동네 편의점 끼니',
      description: '모르는 동네 편의점에서 오늘 한 끼를 해결해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 4), StatBoost('adaptability', 3)], emoji: '🏪',
    ),
    Quest(
      id: 'exp2_n_09', title: '벤치에 앉아 관찰하기',
      description: '공원 벤치에 앉아 20분 동안 지나가는 사람들을 관찰해보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 3), StatBoost('thinking', 3)], emoji: '🪑',
    ),
    Quest(
      id: 'exp2_n_10', title: '자전거로 다른 경로',
      description: '자전거를 이용해 평소 안 가던 경로로 목적지까지 가보세요.',
      category: QuestCategory.exploration, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('exploration', 5), StatBoost('action', 2)], emoji: '🚴',
    ),

    // ── EXPLORATION / CHALLENGE (추가) ─────────────────────────────────
    Quest(
      id: 'exp2_c_01', title: '버스 종점까지 타기',
      description: '무작위 버스를 골라 종점까지 타고 간 뒤 그 근처를 20분 탐험하세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 7), StatBoost('spontaneity', 5)], emoji: '🚍',
    ),
    Quest(
      id: 'exp2_c_02', title: '혼자 공연 보기',
      description: '작은 공연이나 전시회를 혼자 예매해서 감상해보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 6), StatBoost('courage', 5)], emoji: '🎭',
    ),
    Quest(
      id: 'exp2_c_03', title: '일몰 명소 찾아가기',
      description: '일몰 시간에 맞춰 근처 일몰 명소에 가서 해지는 걸 지켜보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 6), StatBoost('spontaneity', 4)], emoji: '🌅',
    ),
    Quest(
      id: 'exp2_c_04', title: '근처 산 정상 올라가기',
      description: '근처 작은 산을 오늘 혼자 올라가보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 7), StatBoost('action', 5)], emoji: '⛰️',
    ),
    Quest(
      id: 'exp2_c_05', title: '인근 도시 카페 탐방',
      description: '평소 잘 안 가는 인근 도시로 이동해 카페에서 2시간 보내보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 7), StatBoost('courage', 4)], emoji: '🏙️',
    ),
    Quest(
      id: 'exp2_c_06', title: '새벽 도시 산책',
      description: '이른 새벽 아직 조용한 시간에 나가서 동네를 혼자 걸어보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 145,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 6), StatBoost('courage', 5)], emoji: '🌙',
    ),
    Quest(
      id: 'exp2_c_07', title: '처음 보는 식재료 요리',
      description: '마트에서 한 번도 써보지 않은 식재료를 사서 요리해보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 5), StatBoost('creativity', 5)], emoji: '🥬',
    ),
    Quest(
      id: 'exp2_c_08', title: '사진 갤러리 혼자 가기',
      description: '사진 전시회나 갤러리를 혼자 예고 없이 방문해보세요.',
      category: QuestCategory.exploration, difficulty: 3, baseXP: 135,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('exploration', 6), StatBoost('creativity', 4)], emoji: '🎨',
    ),

    // ── EXPLORATION / CRAZY (추가) ──────────────────────────────────────
    Quest(
      id: 'exp2_z_01', title: '택시 기사님 추천 장소',
      description: '택시를 타고 "기사님 추천 장소로 가주세요"라고 말해보세요.',
      category: QuestCategory.exploration, difficulty: 4, baseXP: 210,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 8), StatBoost('spontaneity', 7), StatBoost('social', 4)], emoji: '🚕',
    ),
    Quest(
      id: 'exp2_z_02', title: '눈 감고 목적지 정하기',
      description: '지도 앱을 열고 눈 감은 채 탭해서 나온 장소 근처를 탐험하세요.',
      category: QuestCategory.exploration, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 9), StatBoost('spontaneity', 8)], emoji: '🎯',
    ),
    Quest(
      id: 'exp2_z_03', title: '기차 타고 당일치기',
      description: '기차나 버스로 한 정거장 이상 떨어진 낯선 곳에서 당일치기 여행을 해보세요.',
      category: QuestCategory.exploration, difficulty: 5, baseXP: 270,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 12), StatBoost('courage', 6), StatBoost('spontaneity', 5)], emoji: '🚂',
    ),
    Quest(
      id: 'exp2_z_04', title: '일출 원정대',
      description: '오늘 일출 시간에 맞춰 바다나 산에 가서 해 뜨는 걸 직접 보세요.',
      category: QuestCategory.exploration, difficulty: 5, baseXP: 260,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('exploration', 10), StatBoost('courage', 7), StatBoost('action', 5)], emoji: '🌄',
    ),

    // ── SOCIAL / SAFE (추가) ────────────────────────────────────────────
    Quest(
      id: 'soc2_s_01', title: '이름 불러주기',
      description: '오늘 만나는 사람의 이름을 대화 중에 한 번씩 불러주세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3)], emoji: '🗣️',
    ),
    Quest(
      id: 'soc2_s_02', title: '진심 댓글 달기',
      description: '친구 SNS에 단순 좋아요 대신 진심이 담긴 댓글을 달아보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3), StatBoost('creativity', 1)], emoji: '💬',
    ),
    Quest(
      id: 'soc2_s_03', title: '칭찬 문자 보내기',
      description: '지인 한 명에게 진심 어린 칭찬 문자를 보내보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3), StatBoost('relationship', 2)], emoji: '✨',
    ),
    Quest(
      id: 'soc2_s_04', title: '같이 밥 먹자 제안',
      description: '평소 혼자 밥 먹던 시간에 주변 사람에게 같이 먹자고 먼저 제안해보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 4), StatBoost('courage', 2)], emoji: '🍽️',
    ),
    Quest(
      id: 'soc2_s_05', title: '웃으며 먼저 인사',
      description: '오늘 아는 사람 모두에게 내가 먼저 웃으며 인사해보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3)], emoji: '😄',
    ),
    Quest(
      id: 'soc2_s_06', title: '이모티콘 없이 문자',
      description: '친구에게 이모티콘 없이 진심만 담은 문자를 보내보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3), StatBoost('creativity', 2)], emoji: '📩',
    ),
    Quest(
      id: 'soc2_s_07', title: '커피 한 잔 권하기',
      description: '동료나 지인에게 "커피 한 잔 할래요?"라고 먼저 물어보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 4), StatBoost('courage', 1)], emoji: '☕',
    ),
    Quest(
      id: 'soc2_s_08', title: '지인 생일 챙기기',
      description: '이번 달 생일인 지인을 찾아 먼저 축하 메시지를 보내보세요.',
      category: QuestCategory.social, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('social', 3), StatBoost('relationship', 3)], emoji: '🎂',
    ),

    // ── SOCIAL / NORMAL (추가) ──────────────────────────────────────────
    Quest(
      id: 'soc2_n_01', title: '상대방 관심사 먼저 묻기',
      description: '대화 중 상대방의 요즘 관심사를 진심으로 물어보고 10분 이상 듣기',
      category: QuestCategory.social, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('relationship', 3)], emoji: '🎧',
    ),
    Quest(
      id: 'soc2_n_02', title: '고민 털어놓기',
      description: '친한 사람에게 요즘 고민 하나를 솔직하게 털어놓아보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('courage', 3)], emoji: '💭',
    ),
    Quest(
      id: 'soc2_n_03', title: '추억 사진 꺼내 공유',
      description: '오래된 사진 한 장을 꺼내 그 당사자에게 전송해보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 4), StatBoost('relationship', 4)], emoji: '🖼️',
    ),
    Quest(
      id: 'soc2_n_04', title: '모르는 사람 도와주기',
      description: '오늘 도움이 필요해 보이는 사람에게 먼저 다가가 도움을 드리세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('courage', 4)], emoji: '🤲',
    ),
    Quest(
      id: 'soc2_n_05', title: '3명에게 각각 다른 칭찬',
      description: '오늘 3명에게 각각 다른 진심 어린 칭찬을 해보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 6), StatBoost('courage', 2)], emoji: '🌟',
    ),
    Quest(
      id: 'soc2_n_06', title: '처음 만난 사람 이름 기억',
      description: '오늘 처음 소개받은 사람의 이름을 끝까지 기억하고 대화 중 불러보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('thinking', 2)], emoji: '🤝',
    ),
    Quest(
      id: 'soc2_n_07', title: 'SNS에 진심 담긴 글',
      description: '요즘 느끼는 것을 짧게 SNS에 글로 올려보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 4), StatBoost('creativity', 3)], emoji: '📱',
    ),
    Quest(
      id: 'soc2_n_08', title: '동호회 검색하고 가입',
      description: '관심 있는 분야의 지역 동호회를 검색하고 가입 신청해보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 6), StatBoost('courage', 3)], emoji: '🎉',
    ),
    Quest(
      id: 'soc2_n_09', title: '같이 찍은 사진 보내기',
      description: '오늘 만나는 사람과 사진을 한 장 찍어 그 자리에서 바로 전송해보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 4), StatBoost('spontaneity', 3)], emoji: '📸',
    ),
    Quest(
      id: 'soc2_n_10', title: '전화로 안부 묻기',
      description: '문자 대신 전화로 지인에게 안부를 물어보세요.',
      category: QuestCategory.social, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('social', 5), StatBoost('courage', 3)], emoji: '📞',
    ),

    // ── SOCIAL / CHALLENGE (추가) ───────────────────────────────────────
    Quest(
      id: 'soc2_c_01', title: '지역 모임 첫 참가',
      description: '지역 커뮤니티 행사나 소모임에 처음으로 참가해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 8), StatBoost('courage', 6)], emoji: '🏘️',
    ),
    Quest(
      id: 'soc2_c_02', title: '잠잠한 단톡방에 먼저 말 걸기',
      description: '오래 조용했던 단체 채팅방에서 대화를 먼저 시작해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 4)], emoji: '💬',
    ),
    Quest(
      id: 'soc2_c_03', title: '다른 부서 동료와 점심',
      description: '평소 교류 없는 다른 팀/부서 동료에게 점심을 같이 먹자고 제안해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 5)], emoji: '🥗',
    ),
    Quest(
      id: 'soc2_c_04', title: '용기 내어 사과 전하기',
      description: '마음에 걸리는 일이 있었다면 오늘 용기 내어 사과해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 6), StatBoost('courage', 8)], emoji: '🙇',
    ),
    Quest(
      id: 'soc2_c_05', title: '온라인 모임 가입',
      description: '관심 분야 온라인 스터디나 모임을 찾아서 직접 가입해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('exploration', 3)], emoji: '💻',
    ),
    Quest(
      id: 'soc2_c_06', title: '이웃에게 처음 인사',
      description: '같은 건물에 살지만 인사 안 하던 이웃에게 오늘 먼저 인사해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 5)], emoji: '🏠',
    ),
    Quest(
      id: 'soc2_c_07', title: '연락하고 싶던 사람 연락',
      description: '한 번쯤 연락하고 싶었지만 망설였던 사람에게 오늘 먼저 연락해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 145,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 7), StatBoost('courage', 6)], emoji: '📨',
    ),
    Quest(
      id: 'soc2_c_08', title: '지인 소개팅 주선',
      description: '서로 잘 어울릴 것 같은 두 지인을 연결해주거나 소개해보세요.',
      category: QuestCategory.social, difficulty: 3, baseXP: 135,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('social', 8), StatBoost('courage', 4)], emoji: '🤝',
    ),

    // ── SOCIAL / CRAZY (추가) ───────────────────────────────────────────
    Quest(
      id: 'soc2_z_01', title: '낯선 사람과 10분 대화',
      description: '카페나 공원에서 혼자 있는 사람에게 자연스럽게 말을 걸어 10분 이상 대화해보세요.',
      category: QuestCategory.social, difficulty: 4, baseXP: 210,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 9), StatBoost('courage', 8)], emoji: '🌐',
    ),
    Quest(
      id: 'soc2_z_02', title: '즉흥 파티 제안',
      description: '오늘 당장 친구들에게 "지금 만나자!"라고 즉흥 모임을 제안해보세요.',
      category: QuestCategory.social, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 8), StatBoost('spontaneity', 9)], emoji: '🎊',
    ),
    Quest(
      id: 'soc2_z_03', title: '30초 자기소개 낯선 사람에게',
      description: '낯선 사람에게 자신을 30초 안에 소개해보세요.',
      category: QuestCategory.social, difficulty: 5, baseXP: 230,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 10), StatBoost('courage', 9)], emoji: '🎤',
    ),
    Quest(
      id: 'soc2_z_04', title: '랜덤 연락처에 안부',
      description: '연락처에서 무작위로 한 명을 골라 "오랜만이야, 잘 지내?"라고 연락해보세요.',
      category: QuestCategory.social, difficulty: 4, baseXP: 195,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('social', 8), StatBoost('spontaneity', 7), StatBoost('courage', 5)], emoji: '🎲',
    ),

    // ── CREATIVE / SAFE (추가) ──────────────────────────────────────────
    Quest(
      id: 'cre2_s_01', title: '오늘의 색깔 고르기',
      description: '오늘 기분을 색깔 하나로 표현하고, 왜 그 색인지 세 줄 적어보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3), StatBoost('thinking', 2)], emoji: '🎨',
    ),
    Quest(
      id: 'cre2_s_02', title: '손글씨로 짧은 편지',
      description: '누군가에게 손으로 짧은 메시지를 직접 써서 전달해보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3), StatBoost('relationship', 2)], emoji: '✉️',
    ),
    Quest(
      id: 'cre2_s_03', title: '오늘에 영화 제목 붙이기',
      description: '오늘 하루를 영화라고 생각하고 제목을 붙여보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4)], emoji: '🎬',
    ),
    Quest(
      id: 'cre2_s_04', title: '가사 4줄 쓰기',
      description: '오늘 기분에 맞는 노래 가사를 4줄만 직접 써보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4), StatBoost('spontaneity', 1)], emoji: '🎵',
    ),
    Quest(
      id: 'cre2_s_05', title: '주변 물건 의인화',
      description: '지금 있는 물건 하나를 주인공으로 한 짧은 이야기를 3문장으로 만들어보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4), StatBoost('thinking', 2)], emoji: '🖊️',
    ),
    Quest(
      id: 'cre2_s_06', title: '단어 세 개로 오늘 표현',
      description: '오늘을 설명하는 단어 딱 3개를 고르고 각각 이유를 적어보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3), StatBoost('thinking', 2)], emoji: '📝',
    ),
    Quest(
      id: 'cre2_s_07', title: '내 방 베스트 컷',
      description: '내 방에서 가장 마음에 드는 구석을 사진 한 장으로 남겨보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 3)], emoji: '📷',
    ),
    Quest(
      id: 'cre2_s_08', title: '콜라주 만들기',
      description: '잡지나 인쇄물을 오려 붙여 오늘 기분을 표현하는 콜라주를 만들어보세요.',
      category: QuestCategory.creative, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('creativity', 4), StatBoost('spontaneity', 2)], emoji: '✂️',
    ),

    // ── CREATIVE / NORMAL (추가) ────────────────────────────────────────
    Quest(
      id: 'cre2_n_01', title: '기분 맞춤 플레이리스트',
      description: '오늘 기분에 딱 맞는 플레이리스트를 직접 구성해보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('exploration', 2)], emoji: '🎧',
    ),
    Quest(
      id: 'cre2_n_02', title: '옷장 새 코디 시도',
      description: '옷장에 있는 것만으로 평소와 전혀 다른 코디를 조합해보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('spontaneity', 3)], emoji: '👗',
    ),
    Quest(
      id: 'cre2_n_03', title: '레시피 없이 요리하기',
      description: '레시피 없이 냉장고 재료만으로 오늘 한 끼를 만들어보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 6), StatBoost('adaptability', 4)], emoji: '🍳',
    ),
    Quest(
      id: 'cre2_n_04', title: '30초 일상 영상 남기기',
      description: '오늘 인상적인 장면을 30초 영상으로 찍어서 보관해보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('exploration', 2)], emoji: '🎥',
    ),
    Quest(
      id: 'cre2_n_05', title: '방 소품 재배치',
      description: '방 물건 위치를 하나 바꾸거나 소품을 새롭게 배치해보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('adaptability', 3)], emoji: '🛋️',
    ),
    Quest(
      id: 'cre2_n_06', title: '소설 첫 문단 쓰기',
      description: '소설 첫 문단 딱 하나만 써보세요. 마무리 짓지 않아도 됩니다.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 6), StatBoost('thinking', 3)], emoji: '📖',
    ),
    Quest(
      id: 'cre2_n_07', title: '악기 앱으로 즉흥 연주',
      description: '핸드폰 악기 앱을 깔아 5분 동안 즉흥으로 연주해보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 5), StatBoost('spontaneity', 4)], emoji: '🎹',
    ),
    Quest(
      id: 'cre2_n_08', title: '만화 한 컷 그리기',
      description: '오늘 기억에 남는 장면을 만화 한 컷으로 그려보세요. 잘 못 그려도 됩니다.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 6), StatBoost('thinking', 2)], emoji: '🖼️',
    ),
    Quest(
      id: 'cre2_n_09', title: '낯선 소설 장르 도전',
      description: '평소 안 읽던 소설 장르를 골라 20페이지 이상 읽어보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 4), StatBoost('exploration', 3)], emoji: '📕',
    ),
    Quest(
      id: 'cre2_n_10', title: '새 폰트로 메모하기',
      description: '평소와 다른 글씨체로 오늘 일기나 메모를 써보세요.',
      category: QuestCategory.creative, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('creativity', 4), StatBoost('spontaneity', 2)], emoji: '✍️',
    ),

    // ── CREATIVE / CHALLENGE (추가) ─────────────────────────────────────
    Quest(
      id: 'cre2_c_01', title: '10분 자유 글쓰기',
      description: '주제 없이 10분 동안 멈추지 않고 생각나는 대로 글을 써보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('thinking', 4)], emoji: '📝',
    ),
    Quest(
      id: 'cre2_c_02', title: '그림 모방하기',
      description: '마음에 드는 그림 하나를 골라 보고 따라 그려보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 135,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('courage', 4)], emoji: '🖌️',
    ),
    Quest(
      id: 'cre2_c_03', title: '새 언어 인사말 5개',
      description: '한 번도 배워본 적 없는 언어의 기본 인사말 5개를 오늘 외워보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 120,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 5), StatBoost('exploration', 5)], emoji: '🌍',
    ),
    Quest(
      id: 'cre2_c_04', title: '노래 직접 녹음하기',
      description: '좋아하는 노래를 혼자 녹음해서 들어보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 6), StatBoost('courage', 5)], emoji: '🎤',
    ),
    Quest(
      id: 'cre2_c_05', title: '나를 캐릭터로 그리기',
      description: '나를 캐릭터로 표현해서 그려보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('thinking', 3)], emoji: '🦸',
    ),
    Quest(
      id: 'cre2_c_06', title: '처음 보는 창작 앱 도전',
      description: '평소 안 쓰던 창작 앱을 설치해서 결과물 하나를 완성해보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 125,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 6), StatBoost('adaptability', 4)], emoji: '📲',
    ),
    Quest(
      id: 'cre2_c_07', title: '악기 1회 체험',
      description: '드럼, 기타, 피아노 중 하나를 체험할 수 있는 곳을 찾아 신청해보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('courage', 5), StatBoost('exploration', 3)], emoji: '🎸',
    ),
    Quest(
      id: 'cre2_c_08', title: '짧은 영상 편집 완성',
      description: '오늘 찍은 영상을 편집 앱으로 30초 이내 영상으로 만들어보세요.',
      category: QuestCategory.creative, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('creativity', 7), StatBoost('thinking', 3)], emoji: '🎞️',
    ),

    // ── CREATIVE / CRAZY (추가) ─────────────────────────────────────────
    Quest(
      id: 'cre2_z_01', title: '24시간 사진 타임라인',
      description: '오늘 하루 4시간마다 사진을 찍어 타임라인 콜라주를 만들어보세요.',
      category: QuestCategory.creative, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 8), StatBoost('spontaneity', 7)], emoji: '📆',
    ),
    Quest(
      id: 'cre2_z_02', title: '시 낭독 녹음하기',
      description: '직접 쓴 시나 좋아하는 시를 소리 내어 낭독하고 녹음해보세요.',
      category: QuestCategory.creative, difficulty: 4, baseXP: 195,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 8), StatBoost('courage', 7)], emoji: '🎙️',
    ),
    Quest(
      id: 'cre2_z_03', title: '거리 퍼포먼스 구경 or 참여',
      description: '버스킹이나 거리 공연을 찾아가거나, 직접 작은 퍼포먼스를 해보세요.',
      category: QuestCategory.creative, difficulty: 5, baseXP: 250,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 9), StatBoost('courage', 9), StatBoost('social', 4)], emoji: '🎪',
    ),
    Quest(
      id: 'cre2_z_04', title: '1분 즉흥 코미디',
      description: '친한 친구에게 1분짜리 즉흥 이야기를 만들어 들려주세요.',
      category: QuestCategory.creative, difficulty: 4, baseXP: 185,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('creativity', 8), StatBoost('spontaneity', 8), StatBoost('courage', 5)], emoji: '🤡',
    ),

    // ── THINKING / SAFE (추가) ──────────────────────────────────────────
    Quest(
      id: 'thi2_s_01', title: '오늘 가장 좋은 순간',
      description: '오늘 가장 좋았던 순간 하나를 떠올리고 왜 좋았는지 3가지 적어보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('creativity', 2)], emoji: '🌟',
    ),
    Quest(
      id: 'thi2_s_02', title: '감사 세 가지 적기',
      description: '오늘 감사한 것 3가지를 구체적으로 적어보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('adaptability', 2)], emoji: '🙏',
    ),
    Quest(
      id: 'thi2_s_03', title: '내 강점 세 가지',
      description: '스스로 생각하는 강점 3가지와 그 이유를 솔직하게 적어보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 4)], emoji: '💪',
    ),
    Quest(
      id: 'thi2_s_04', title: '롤모델이라면?',
      description: '내 롤모델이 지금 내 상황이라면 어떻게 할지 상상해보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('creativity', 2)], emoji: '🦅',
    ),
    Quest(
      id: 'thi2_s_05', title: '오늘 배운 것 하나',
      description: '오늘 새로 알게 된 것이나 깨달은 것 하나를 짧게 정리해보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3)], emoji: '💡',
    ),
    Quest(
      id: 'thi2_s_06', title: '걱정 목록 분류하기',
      description: '지금 마음에 걸리는 것들을 적고, 내가 통제할 수 있는 것과 없는 것으로 나눠보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 4), StatBoost('adaptability', 2)], emoji: '📋',
    ),
    Quest(
      id: 'thi2_s_07', title: '지금 이 순간 다섯 가지',
      description: '지금 이 순간 느끼는 것 5가지를 감각별로 써보세요. (보이는 것, 들리는 것 등)',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3)], emoji: '🧘',
    ),
    Quest(
      id: 'thi2_s_08', title: '어제 시간 돌아보기',
      description: '어제 하루 시간을 어떻게 썼는지 간단히 돌아보세요.',
      category: QuestCategory.thinking, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('thinking', 3), StatBoost('adaptability', 1)], emoji: '⏱️',
    ),

    // ── THINKING / NORMAL (추가) ────────────────────────────────────────
    Quest(
      id: 'thi2_n_01', title: '1년 후 나에게 편지',
      description: '1년 후 나에게 보내는 짧은 편지를 써보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('creativity', 4)], emoji: '📬',
    ),
    Quest(
      id: 'thi2_n_02', title: '관심사 30분 깊게 파기',
      description: '요즘 궁금한 것 하나를 골라 30분 동안 집중적으로 찾아보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('exploration', 3)], emoji: '🔬',
    ),
    Quest(
      id: 'thi2_n_03', title: '뉴스 한 줄 요약',
      description: '오늘 뉴스 기사 하나를 읽고 핵심을 한 줄로 요약해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 80,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('adaptability', 2)], emoji: '📰',
    ),
    Quest(
      id: 'thi2_n_04', title: '다음 달 목표 설정',
      description: '다음 달 이루고 싶은 작은 목표 하나를 구체적으로 정해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('courage', 3)], emoji: '🎯',
    ),
    Quest(
      id: 'thi2_n_05', title: '다른 직업 상상',
      description: '지금과 다른 직업을 가졌다면 어떤 삶일지 구체적으로 상상해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('creativity', 3)], emoji: '🔭',
    ),
    Quest(
      id: 'thi2_n_06', title: '몰랐던 것 인정하고 공부',
      description: '안다고 생각했지만 사실 잘 모르는 것 하나를 인정하고 오늘 제대로 공부해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('courage', 3)], emoji: '📚',
    ),
    Quest(
      id: 'thi2_n_07', title: '나쁜 습관 분석',
      description: '내 안 좋은 습관 하나를 왜 계속하는지 이유를 3가지 써보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('adaptability', 4)], emoji: '🔍',
    ),
    Quest(
      id: 'thi2_n_08', title: '과거 결정 재평가',
      description: '과거에 내린 결정 하나를 지금 시점에서 다시 평가해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('adaptability', 3)], emoji: '⚖️',
    ),
    Quest(
      id: 'thi2_n_09', title: '독서 노트 한 페이지',
      description: '최근 읽은 책이나 글에서 인상 깊은 구절과 이유를 적어보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 5), StatBoost('creativity', 3)], emoji: '📓',
    ),
    Quest(
      id: 'thi2_n_10', title: '가치관 우선순위 정하기',
      description: '내 삶에서 중요한 것들의 우선순위를 1위부터 5위까지 정해보세요.',
      category: QuestCategory.thinking, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 6), StatBoost('courage', 2)], emoji: '🏆',
    ),

    // ── THINKING / CHALLENGE (추가) ─────────────────────────────────────
    Quest(
      id: 'thi2_c_01', title: '나만의 철학 써보기',
      description: '내 삶의 원칙이나 철학 하나를 글로 써보세요. 3문장 이상.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('creativity', 4)], emoji: '🦉',
    ),
    Quest(
      id: 'thi2_c_02', title: '10년 후 나 상상하기',
      description: '10년 후 내 모습을 구체적으로 상상하고 하루 일과로 묘사해보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('creativity', 4)], emoji: '🌠',
    ),
    Quest(
      id: 'thi2_c_03', title: '두려움 글로 마주하기',
      description: '가장 두렵게 느껴지는 것 하나를 글로 솔직하게 써보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 6), StatBoost('courage', 7)], emoji: '👁️',
    ),
    Quest(
      id: 'thi2_c_04', title: '이 일을 하는 이유',
      description: '지금 하고 있는 일(공부, 직장, 활동)의 의미를 이유 3가지로 써보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 125,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('courage', 4)], emoji: '🧭',
    ),
    Quest(
      id: 'thi2_c_05', title: '논거 3개로 주장하기',
      description: '논쟁적인 주제를 하나 골라 내 의견을 논거 3가지로 써보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('courage', 4)], emoji: '⚔️',
    ),
    Quest(
      id: 'thi2_c_06', title: '내 삶의 결핍 찾기',
      description: '지금 내 삶에서 부족한 것 하나를 솔직하게 인식하고 원인을 써보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 135,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('courage', 5)], emoji: '🔐',
    ),
    Quest(
      id: 'thi2_c_07', title: '내 정보 출처 점검하기',
      description: '평소 믿던 정보 하나를 다른 시각으로 검토하고 출처를 확인해보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 120,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('adaptability', 3)], emoji: '🕵️',
    ),
    Quest(
      id: 'thi2_c_08', title: '버려야 할 믿음 찾기',
      description: '오래 갖고 있었지만 이제 버려야 할 생각이나 믿음 하나를 써보세요.',
      category: QuestCategory.thinking, difficulty: 3, baseXP: 130,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('thinking', 7), StatBoost('adaptability', 5)], emoji: '🗑️',
    ),

    // ── THINKING / CRAZY (추가) ─────────────────────────────────────────
    Quest(
      id: 'thi2_z_01', title: '20분 의식의 흐름 글쓰기',
      description: '20분 동안 멈추지 않고 생각나는 대로 계속 써보세요.',
      category: QuestCategory.thinking, difficulty: 4, baseXP: 190,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('thinking', 8), StatBoost('creativity', 7)], emoji: '🌀',
    ),
    Quest(
      id: 'thi2_z_02', title: '타인의 시선으로 나 쓰기',
      description: '나를 잘 아는 사람이 나를 어떻게 볼지, 그 사람 입장에서 나를 묘사해보세요.',
      category: QuestCategory.thinking, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('thinking', 9), StatBoost('courage', 6)], emoji: '🪞',
    ),
    Quest(
      id: 'thi2_z_03', title: '묘비명 써보기',
      description: '삶의 의미를 생각해보기 위해, 내 묘비명을 지금 써보세요.',
      category: QuestCategory.thinking, difficulty: 5, baseXP: 240,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('thinking', 10), StatBoost('courage', 8)], emoji: '⚱️',
    ),
    Quest(
      id: 'thi2_z_04', title: '10가지 가정 뒤집기',
      description: '오늘 했던 가정이나 믿음 10가지를 완전히 반대로 생각해보세요.',
      category: QuestCategory.thinking, difficulty: 4, baseXP: 210,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('thinking', 9), StatBoost('adaptability', 6)], emoji: '🔄',
    ),

    // ── ACTION / SAFE (추가) ────────────────────────────────────────────
    Quest(
      id: 'act2_s_01', title: '전신 스트레칭 5분',
      description: '지금 바로 5분 동안 전신 스트레칭을 해보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3)], emoji: '🤸',
    ),
    Quest(
      id: 'act2_s_02', title: '물 두 잔 마시기',
      description: '지금 당장 물 두 잔을 마셔보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 35,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 2), StatBoost('adaptability', 1)], emoji: '💧',
    ),
    Quest(
      id: 'act2_s_03', title: '30분 일찍 기상',
      description: '내일 평소보다 30분 일찍 일어나보세요. 오늘 알람을 설정해두세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3), StatBoost('courage', 2)], emoji: '⏰',
    ),
    Quest(
      id: 'act2_s_04', title: '점심 산책 5분',
      description: '점심시간에 5분 이상 밖으로 나가 걸어보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3), StatBoost('exploration', 1)], emoji: '🌞',
    ),
    Quest(
      id: 'act2_s_05', title: '식후 소화 산책',
      description: '식사 후 10분 동안 소화 산책을 해보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3)], emoji: '🚶',
    ),
    Quest(
      id: 'act2_s_06', title: '바른 자세 30분',
      description: '30분 동안 의식적으로 허리를 펴고 바른 자세를 유지해보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 40,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 2), StatBoost('courage', 1)], emoji: '🧍',
    ),
    Quest(
      id: 'act2_s_07', title: '냉수 샤워 마지막 1분',
      description: '샤워 마지막 1분을 차가운 물로 마무리해보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 3), StatBoost('courage', 3)], emoji: '🚿',
    ),
    Quest(
      id: 'act2_s_08', title: '핸드폰 30분 멀리 두기',
      description: '30분 동안 핸드폰을 눈에 보이지 않는 곳에 두고 생활해보세요.',
      category: QuestCategory.action, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('action', 2), StatBoost('thinking', 2)], emoji: '📵',
    ),

    // ── ACTION / NORMAL (추가) ──────────────────────────────────────────
    Quest(
      id: 'act2_n_01', title: '오늘 1만 보 채우기',
      description: '오늘 하루 만 보를 채워보세요. 만보기 앱을 활용해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('exploration', 2)], emoji: '👟',
    ),
    Quest(
      id: 'act2_n_02', title: '줄넘기 100개',
      description: '줄넘기 100개를 오늘 완료해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('courage', 2)], emoji: '🪃',
    ),
    Quest(
      id: 'act2_n_03', title: '계단으로 5층 오르내리기',
      description: '오늘 하루 계단을 이용해 5층 이상 오르내려보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('courage', 2)], emoji: '🪜',
    ),
    Quest(
      id: 'act2_n_04', title: '맨몸 운동 루틴 1세트',
      description: '팔굽혀펴기, 스쿼트, 플랭크를 각 10개씩 해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('courage', 3)], emoji: '💪',
    ),
    Quest(
      id: 'act2_n_05', title: '자전거 30분 이동',
      description: '자전거를 타고 30분 이상 이동해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('exploration', 3)], emoji: '🚵',
    ),
    Quest(
      id: 'act2_n_06', title: '댄스 영상 따라하기',
      description: '유튜브에서 댄스 영상 하나를 찾아 10분 이상 따라해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('spontaneity', 4)], emoji: '💃',
    ),
    Quest(
      id: 'act2_n_07', title: '초급 요가 10분',
      description: '초급 요가 영상을 찾아 10분 이상 따라해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 4), StatBoost('adaptability', 4)], emoji: '🧘',
    ),
    Quest(
      id: 'act2_n_08', title: '헬스장 방문하기',
      description: '가까운 헬스장에 방문해 30분 이상 운동해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 6), StatBoost('courage', 3)], emoji: '🏋️',
    ),
    Quest(
      id: 'act2_n_09', title: '농구 자유투 10개',
      description: '동네 농구장에서 자유투 10개를 던져보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 5), StatBoost('spontaneity', 3)], emoji: '🏀',
    ),
    Quest(
      id: 'act2_n_10', title: '수영장 처음 가보기',
      description: '근처 수영장에 방문해 처음으로 수영을 해보세요.',
      category: QuestCategory.action, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('action', 6), StatBoost('courage', 4)], emoji: '🏊',
    ),

    // ── ACTION / CHALLENGE (추가) ───────────────────────────────────────
    Quest(
      id: 'act2_c_01', title: '5km 달리기',
      description: '오늘 5km를 달려보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 8), StatBoost('courage', 5)], emoji: '🏃',
    ),
    Quest(
      id: 'act2_c_02', title: '클라이밍 1회 체험',
      description: '볼더링 센터를 찾아 1회 체험을 해보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 6), StatBoost('exploration', 3)], emoji: '🧗',
    ),
    Quest(
      id: 'act2_c_03', title: '저녁 달리기 20분',
      description: '저녁에 동네를 20분 동안 달려보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 140,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 4)], emoji: '🌆',
    ),
    Quest(
      id: 'act2_c_04', title: '등산 도전',
      description: '근처 산을 찾아 정상까지 오르고 내려오세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 170,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 8), StatBoost('courage', 5), StatBoost('exploration', 4)], emoji: '🏔️',
    ),
    Quest(
      id: 'act2_c_05', title: '자전거로 10km 이상',
      description: '자전거를 타고 10km 이상 이동해보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 155,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('exploration', 5)], emoji: '🚴',
    ),
    Quest(
      id: 'act2_c_06', title: '수영 25m 완주',
      description: '수영장에서 25m를 쉬지 않고 완주해보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 5)], emoji: '🏊',
    ),
    Quest(
      id: 'act2_c_07', title: '엘리베이터 없는 하루',
      description: '오늘 하루 엘리베이터를 전혀 이용하지 않아보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 145,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 4)], emoji: '🪜',
    ),
    Quest(
      id: 'act2_c_08', title: '크로스핏 체험',
      description: '근처 크로스핏 센터의 1회 체험 수업에 신청해보세요.',
      category: QuestCategory.action, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('action', 8), StatBoost('courage', 5), StatBoost('exploration', 3)], emoji: '🏋️',
    ),

    // ── ACTION / CRAZY (추가) ───────────────────────────────────────────
    Quest(
      id: 'act2_z_01', title: '새벽 러닝',
      description: '새벽 6시 이전에 일어나 달리기를 해보세요.',
      category: QuestCategory.action, difficulty: 5, baseXP: 240,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 9), StatBoost('courage', 9), StatBoost('spontaneity', 5)], emoji: '🌅',
    ),
    Quest(
      id: 'act2_z_02', title: '마라톤 대회 신청',
      description: '10km 마라톤 대회를 오늘 검색해서 신청해보세요.',
      category: QuestCategory.action, difficulty: 4, baseXP: 220,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 9), StatBoost('courage', 8), StatBoost('spontaneity', 6)], emoji: '🏅',
    ),
    Quest(
      id: 'act2_z_03', title: '번지점프 예약',
      description: '번지점프나 집라인 체험을 오늘 검색해서 예약해보세요.',
      category: QuestCategory.action, difficulty: 5, baseXP: 280,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 10), StatBoost('courage', 12), StatBoost('spontaneity', 6)], emoji: '🪂',
    ),
    Quest(
      id: 'act2_z_04', title: 'SNS 디지털 디톡스 하루',
      description: '오늘 하루 모든 SNS 앱을 삭제하거나 로그아웃하고 생활해보세요.',
      category: QuestCategory.action, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('action', 7), StatBoost('courage', 7), StatBoost('thinking', 5)], emoji: '📴',
    ),

    // ── RELATIONSHIP / SAFE (추가) ──────────────────────────────────────
    Quest(
      id: 'rel2_s_01', title: '가족 사진 꺼내 보내기',
      description: '오래된 가족 사진 하나를 꺼내 그 가족 구성원에게 전송해보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 2)], emoji: '🖼️',
    ),
    Quest(
      id: 'rel2_s_02', title: '부모님께 전화 한 통',
      description: '오늘 부모님께 전화를 한 통 드려보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 55,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 2)], emoji: '☎️',
    ),
    Quest(
      id: 'rel2_s_03', title: '오늘 있던 일 공유하기',
      description: '친한 사람에게 오늘 있었던 재미있는 일을 공유해보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 3), StatBoost('social', 3)], emoji: '😂',
    ),
    Quest(
      id: 'rel2_s_04', title: '처음 만남의 기억 물어보기',
      description: '오래 알고 지낸 사람에게 처음 만났을 때의 기억을 물어보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 2)], emoji: '💫',
    ),
    Quest(
      id: 'rel2_s_05', title: '도움 받은 것 감사 전달',
      description: '최근 도움받았던 사람에게 뒤늦게라도 감사 메시지를 보내보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('courage', 2)], emoji: '🌷',
    ),
    Quest(
      id: 'rel2_s_06', title: '가족 두 가지 칭찬',
      description: '가족이나 친구의 좋은 점 두 가지를 직접 말해주세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 2)], emoji: '🌸',
    ),
    Quest(
      id: 'rel2_s_07', title: 'SNS 옛 친구 반갑다 인사',
      description: 'SNS에서 오래전에 알던 친구를 찾아 반갑다는 메시지를 보내보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 50,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 4), StatBoost('social', 3)], emoji: '👋',
    ),
    Quest(
      id: 'rel2_s_08', title: '좋아하는 것 추천해주기',
      description: '요즘 좋아하는 책, 영상, 음식 등을 지인에게 추천해보세요.',
      category: QuestCategory.relationship, difficulty: 1, baseXP: 45,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('relationship', 3), StatBoost('social', 2)], emoji: '💌',
    ),

    // ── RELATIONSHIP / NORMAL (추가) ────────────────────────────────────
    Quest(
      id: 'rel2_n_01', title: '같이 산책 제안하기',
      description: '가족이나 친구에게 같이 산책하자고 먼저 제안해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 3), StatBoost('action', 2)], emoji: '🚶‍♂️',
    ),
    Quest(
      id: 'rel2_n_02', title: '어색한 관계 먼저 풀기',
      description: '어색하게 지내던 사람에게 먼저 연락해 가볍게 대화를 시작해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('courage', 5)], emoji: '🕊️',
    ),
    Quest(
      id: 'rel2_n_03', title: '밥 한 번 사기',
      description: '오래 못 본 지인에게 밥 한 번 살게 만나자고 제안해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 4)], emoji: '🍜',
    ),
    Quest(
      id: 'rel2_n_04', title: '목소리로 연락하기',
      description: '문자 대신 전화나 음성 메시지로 오랜 친구에게 안부를 전해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 95,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('social', 4), StatBoost('courage', 2)], emoji: '📞',
    ),
    Quest(
      id: 'rel2_n_05', title: '힘든 지인 먼저 챙기기',
      description: '요즘 힘들어 보이는 친구에게 먼저 연락해 들어주세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 105,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('social', 4)], emoji: '🫂',
    ),
    Quest(
      id: 'rel2_n_06', title: '함께 요리하기',
      description: '가족이나 친구와 함께 요리를 만들어보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('creativity', 3)], emoji: '👨‍🍳',
    ),
    Quest(
      id: 'rel2_n_07', title: '기념일 서프라이즈',
      description: '소중한 사람의 기념일을 챙겨 작은 서프라이즈를 해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 110,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('creativity', 3)], emoji: '🎁',
    ),
    Quest(
      id: 'rel2_n_08', title: '가족 단체 사진',
      description: '가족이 모인 자리에서 단체 사진 한 장을 찍어보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('spontaneity', 2)], emoji: '📷',
    ),
    Quest(
      id: 'rel2_n_09', title: '선생님·멘토에게 안부',
      description: '예전 선생님이나 멘토에게 근황 안부를 전해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 6), StatBoost('courage', 4)], emoji: '🎓',
    ),
    Quest(
      id: 'rel2_n_10', title: '함께 운동하자 제안',
      description: '운동 파트너를 만들어서 같이 운동하자고 제안해보세요.',
      category: QuestCategory.relationship, difficulty: 2, baseXP: 100,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('relationship', 5), StatBoost('action', 3), StatBoost('social', 3)], emoji: '🤜',
    ),

    // ── RELATIONSHIP / CHALLENGE (추가) ─────────────────────────────────
    Quest(
      id: 'rel2_c_01', title: '끊겼던 사람에게 먼저 연락',
      description: '연락이 끊겼던 사람에게 먼저 만나자고 용기 내어 제안해보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 155,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 8), StatBoost('courage', 7)], emoji: '🔗',
    ),
    Quest(
      id: 'rel2_c_02', title: '마음 속 말 꺼내기',
      description: '오랫동안 마음 속에 있던 말을 용기 내어 직접 전달해보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 8), StatBoost('courage', 8)], emoji: '💬',
    ),
    Quest(
      id: 'rel2_c_03', title: '가족 여행 즉흥 제안',
      description: '가족에게 갑작스럽게 가까운 여행을 제안해보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 150,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('spontaneity', 7)], emoji: '🚗',
    ),
    Quest(
      id: 'rel2_c_04', title: '소모임 직접 만들기',
      description: '관심사가 맞는 사람들과 함께할 소모임을 직접 만들어보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 160,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('social', 6), StatBoost('courage', 4)], emoji: '🏘️',
    ),
    Quest(
      id: 'rel2_c_05', title: '멀리 사는 친구 찾아가기',
      description: '오래 못 만난 먼 친구를 직접 찾아가보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 170,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 8), StatBoost('courage', 5), StatBoost('exploration', 4)], emoji: '✈️',
    ),
    Quest(
      id: 'rel2_c_06', title: '갈등 직접 대화로 해결',
      description: '피하고 있던 어려운 대화를 오늘 직접 나눠보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 170,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 8), StatBoost('courage', 9)], emoji: '🤝',
    ),
    Quest(
      id: 'rel2_c_07', title: '부모님께 이유 없는 선물',
      description: '특별한 날이 아닌데 부모님께 작은 선물을 해보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 145,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('spontaneity', 5)], emoji: '🌹',
    ),
    Quest(
      id: 'rel2_c_08', title: '지인 두 명 서로 소개',
      description: '서로 어울릴 것 같은 두 지인을 직접 소개해주거나 함께 만나보세요.',
      category: QuestCategory.relationship, difficulty: 3, baseXP: 145,
      comfortLevel: ComfortLevel.challenge,
      statBoosts: [StatBoost('relationship', 7), StatBoost('social', 6)], emoji: '👥',
    ),

    // ── RELATIONSHIP / CRAZY (추가) ─────────────────────────────────────
    Quest(
      id: 'rel2_z_01', title: '랜덤 연락처에 안부',
      description: '연락처에서 무작위로 한 명을 골라 "오랜만이야, 잘 지내?"라고 연락해보세요.',
      category: QuestCategory.relationship, difficulty: 4, baseXP: 190,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('relationship', 8), StatBoost('spontaneity', 8), StatBoost('courage', 5)], emoji: '🎲',
    ),
    Quest(
      id: 'rel2_z_02', title: '예고 없이 찾아가기',
      description: '친한 친구나 가족에게 예고 없이 찾아가보세요.',
      category: QuestCategory.relationship, difficulty: 4, baseXP: 200,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('relationship', 9), StatBoost('spontaneity', 9), StatBoost('courage', 5)], emoji: '🚪',
    ),
    Quest(
      id: 'rel2_z_03', title: '관계 지도 그려보기',
      description: '내 인간관계를 종이에 시각적으로 그려보고 소홀한 관계를 찾아보세요.',
      category: QuestCategory.relationship, difficulty: 4, baseXP: 180,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('relationship', 8), StatBoost('thinking', 7)], emoji: '🗺️',
    ),
    Quest(
      id: 'rel2_z_04', title: '인생 편지 쓰기',
      description: '가장 소중한 사람에게 평생 간직할 수 있는 진심 담긴 편지를 써보세요.',
      category: QuestCategory.relationship, difficulty: 5, baseXP: 250,
      comfortLevel: ComfortLevel.crazy,
      statBoosts: [StatBoost('relationship', 12), StatBoost('courage', 8), StatBoost('creativity', 5)], emoji: '💝',
    ),

    // ── RANDOM ──────────────────────────────────────────────────────────
    Quest(
      id: 'rnd_01',
      title: '5분 명상',
      description: '지금 바로 5분 동안 눈을 감고 호흡에만 집중해보세요.\n생각이 많아도 괜찮습니다.',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('thinking', 4), StatBoost('adaptability', 3)],
      emoji: '🧘',
    ),
    Quest(
      id: 'rnd_02',
      title: '동전으로 결정',
      description: '오늘 작은 선택 하나를 동전 던지기로 결정해보세요.\n저녁 메뉴, 이동 방향 무엇이든 좋습니다.',
      category: QuestCategory.random,
      difficulty: 1,
      baseXP: 70,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('spontaneity', 5)],
      emoji: '🪙',
    ),
    Quest(
      id: 'rnd_03',
      title: '오늘의 다짐 하나',
      description: '오늘 하루 동안 지킬 작은 규칙 하나를 스스로 만들어보세요.\n예: "오늘은 엘리베이터 안 탄다"',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 85,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('courage', 3), StatBoost('adaptability', 3)],
      emoji: '🎯',
    ),
    Quest(
      id: 'rnd_04',
      title: '버킷리스트 하나 적기',
      description: '언젠가 해보고 싶은 것을 딱 하나 적어두세요.\n실현 가능 여부는 중요하지 않습니다.',
      category: QuestCategory.random,
      difficulty: 1,
      baseXP: 65,
      comfortLevel: ComfortLevel.safe,
      statBoosts: [StatBoost('spontaneity', 3), StatBoost('creativity', 3)],
      emoji: '📋',
    ),
    Quest(
      id: 'rnd_05',
      title: '평소 안 보던 콘텐츠 끝까지 보기',
      description: '평소 관심 없던 장르의 영상이나 글을 하나 선택해서 끝까지 보세요.',
      category: QuestCategory.random,
      difficulty: 2,
      baseXP: 90,
      comfortLevel: ComfortLevel.normal,
      statBoosts: [StatBoost('adaptability', 4), StatBoost('thinking', 3)],
      emoji: '📺',
    ),
  ];

  static Quest? findById(String id) {
    try {
      return all.firstWhere((q) => q.id == id);
    } catch (_) {
      return null;
    }
  }
}
